--FINETDB
CREATE DATABASE FinetDB;

USE FinetDB;

CREATE TABLE MsUser(
	[UserID] UNIQUEIDENTIFIER PRIMARY KEY,
	[Username] VARCHAR(255) UNIQUE,
	[Email] VARCHAR(255) UNIQUE,
	[Password] VARCHAR(255)
);

SELECT *FROM MsUser;

CREATE TABLE TrExpense(
	[ExpenseID] UNIQUEIDENTIFIER PRIMARY KEY,
	[MethodID] INT FOREIGN KEY REFERENCES MsMethod(MethodID),
	[ECategoryID] INT FOREIGN KEY REFERENCES MsExpenseCategory(ECategoryID),
	[Title] VARCHAR(255),
	[Description] VARCHAR(255),
	[Amount] INT,
	[CreatedAt] DATETIME,
	[Stsrc] VARCHAR(1)
);

SELECT *FROM TrExpense;

CREATE TABLE MsMethod(
    [MethodID] INT PRIMARY KEY IDENTITY(1,1),
    [MethodName] VARCHAR(255),
	[Stsrc] VARCHAR(1)
);

SELECT *FROM MsMethod;

CREATE TABLE MsExpenseCategory(
	[ECategoryID] INT PRIMARY KEY IDENTITY(1,1),
	[ECategoryName] VARCHAR(255),
	[Stsrc] VARCHAR(1)
);

SELECT *FROM MsExpenseCategory;

-- SELECT TABLE
SELECT *FROM TrExpense;
SELECT *FROM MsExpenseCategory;
SELECT *FROM MsMethod;

--DROP TABLE
DROP TABLE MsUser;
DROP TABLE TrExpense;
DROP TABLE MsExpenseCategory;
DROP TABLE MsMethod;